image: rust:1.97.1@sha256:1bcff4befb740599103a2c7cb51058e14479b2e35e3a34a3f0dc4ede09927488

default:
  timeout: 10 hours

stages:
  - build
  - e2e
  - sonarqube

variables:
  NODE_VERSION: 24.15.0
  DENO_VERSION: 2.8.3
  DENO_DIR: "${CI_PROJECT_DIR}/.deno"

include:
  - local: ".gitlab/ci/build.yml"
  - local: ".gitlab/ci/e2e-vm.yml"
  - local: ".gitlab/ci/sonarqube.yml"
