sonar.projectKey=Sonar-team_Sonar_desktop_app
sonar.organization=sonar-team

sonar.projectName=SONAR Desktop App

sonar.sources=src,src-tauri/src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.scannerwork/**,src-tauri/vendor/**,**/vendor/**,**/*.lock
