name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libpcap-dev

      - name: Install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          choco install winpcap -y
          echo "WinPcap installed"
          (new-object System.Net.WebClient).DownloadFile('https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip','WpdPack_4_1_2.zip')
          7z x WpdPack_4_1_2.zip
          echo "LIB=$env:GITHUB_WORKSPACE\WpdPack\Lib\x64\" >> $env:GITHUB_ENV
          echo "WinPcap Developers Pack installed"

      - name: Install app dependencies and build web
        run: yarn && yarn build

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: 1.1.1 # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v1.1.1'
          releaseBody: '#### Version 1.1.1

          **Nouvelles fonctionnalités :**
          - **Enregistrement de la vue graphique au format SVG :** Il est désormais possible d'enregistrer la vue graphique de vos données réseau au format SVG. Cette fonctionnalité permet une préservation de haute qualité de vos visualisations pour une utilisation dans des rapports ou des présentations. Pour sauvegarder votre visualisation, sélectionnez l'option 'Sauvegarder en SVG' depuis la vue graphique.
          
          - **Affichage des protocoles sur les arêtes :** Les visualisations graphiques ont été améliorées pour afficher les protocoles qui interagissent entre les adresses MAC. Cette mise à jour enrichit l'analyse en offrant une compréhension immédiate des types de communications se déroulant au sein de votre réseau, permettant ainsi d'identifier plus facilement les modèles de trafic et les éventuelles anomalies.'
          releaseDraft: true
          prerelease: false