name: coverage

on: [push]

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        run: |
          apt-get update
          apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libpcap-dev

      - name: Install app dependencies and build web
        run: yarn && yarn build
        
      - name: Debug information
        run: |
          pwd
          echo "pwd exit status: $?"
          ls -a
          echo "LS exit status: $?"
        shell: bash --noprofile --norc -e -o pipefail {0}

      # Combine directory change with Rust project build in a single step
      - name: Build Rust project in src-tauri directory
        run: |
          cd src-tauri
          cargo build --verbose
          ls -a # List contents to verify
        shell: bash --noprofile --norc -e -o pipefail {0}

      - name: Generate code coverage
        run: |
          cd src-tauri
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
        shell: bash --noprofile --norc -e -o pipefail {0}

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
