name: "Create Documentation"
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libpcap-dev

      - name: Install web dependencies
        run: yarn && yarn build

      - name: Publish to Crates.io
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        working-directory: ./src-tauri
        run: |
          cargo login $CRATES_IO_TOKEN
          cargo publish --verbose --allow-dirty
          
